
title: JoaquimBellmunt
url: 'http://junlulocky.com'
baseurl: '/PanelCV' #change it according to your repository name



# Profile information
yourname: Joaquim Bellmunt Montoya  ## put your name
title: 'PhD, Computer Science & AI'  ## your title
location: Singapore


## Social Profiles
# facebook: http://www.facebook.com  ## your facebook account url
twitter: https://twitter.com/quimbellm  ## your twitter account url
linkedin: https://www.linkedin.com/in/joaquimbellmunt/  ## your linkedin account url
github: https://github.com/JoaquimBellmunt
# dribbble: http://www.dribble.com  ## you dribbble account url
# foursquare: http://www.foursquare.com  ## your foursquare account url



# Update all the sections by editing the files inside _includes folder.
